### ISSUE TITLE
运行环境后，进入登陆网站闪退。查询得知跟'find_element_by_name'有关，求大佬解答。

### ISSUE THREAD

**Issue by Wekay** [MakiNaruto/Automatic_ticket_purchase#29]
编译器报出问题如下：
Traceback (most recent call last):
  File "C:/Users/ATiS/Downloads/Automatic_ticket_purchase-master/Automatic_ticket_purchase-master/Automatic_ticket_purchase.py", line 315, in <module>
    a.run()
  File "C:/Users/ATiS/Downloads/Automatic_ticket_purchase-master/Automatic_ticket_purchase-master/Automatic_ticket_purchase.py", line 235, in run
    self.login_cookies = tools.account_login('account', self.login_id, self.login_password)
  File "C:\Users\ATiS\Downloads\Automatic_ticket_purchase-master\Automatic_ticket_purchase-master\tools.py", line 105, in account_login
    driver.find_element_by_name('fm-login-id').send_keys(login_id)
AttributeError: 'WebDriver' object has no attribute 'find_element_by_name'

进程已结束,退出代码1

**Comment by Wekay** [comment]
emm。不确定是否能解决问题，正在尝试。

**Comment by xiangjiayu** [comment]
from selenium.webdriver.common.by import By

driver.find_element(By.ID,'fm-login-id').send_keys(login_id)
driver.find_element(By.ID,'fm-login-password').send_keys(login_password)
driver.find_element(By.CLASS_NAME,'password-login').send_keys(Keys.ENTER)

**Comment by jyk0201** [comment]
这边大麦bp，脚本，代码和猫眼bp可长期提供，有需要的来➕q2814249606，备注github。主打信任不扯皮
