### ISSUE TITLE
打开chrome浏览器 登录大麦后就没有其他反馈了

### ISSUE THREAD

**Issue by CainChao** [MakiNaruto/Automatic_ticket_purchase#39]

**Comment by Gavin-U** [comment]
，麻烦问一下怎么配置得，chrome打不开

**Comment by jyk0201** [comment]
这边大麦bp，脚本，代码和猫眼bp可长期提供，有需要的来➕q2814249606，备注github。主打信任不扯皮

**Comment by TLGits** [comment]
同遇到了该问题

**Comment by gg970856489** [comment]
DevTools listening on ws://127.0.0.1:50140/devtools/browser/4380ba58-1188-4620-b466-b6088f27fd9f
Traceback (most recent call last):
  File "C:\Users\97085\Desktop\Automatic_ticket_purchase-master\Automatic_ticket_purchase.py", line 315, in <module>
    a.run()
[8920:7072:0924/150406.036:ERROR:device_event_log_impl.cc(214)] [15:04:06.036] USB: usb_service_win.cc:415 Could not read device interface GUIDs: 系统找不到指定的文件。 (0x2)
  File "C:\Users\97085\Desktop\Automatic_ticket_purchase-master\Automatic_ticket_purchase.py", line 245, in run
[8920:7072:0924/150406.214:ERROR:device_event_log_impl.cc(214)] [15:04:06.216] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: 连到系统上的设备没有发挥作用。 (0x1F)
    tools.save_cookies(self.login_cookies)
  File "C:\Users\97085\Desktop\Automatic_ticket_purchase-master\tools.py", line 26, in save_cookies
[8920:7072:0924/150406.801:ERROR:device_event_log_impl.cc(214)] [15:04:06.802] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: 连到系统上的设备没有发挥作用。 (0x1F)
    with open('cookies.pkl', 'wb') as fw:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'cookies.pkl'
我问chatgpt它回复说错误信息 "PermissionError: [Errno 13] Permission denied: 'cookies.pkl'" 表示你的脚本没有权限在当前目录下创建或写入名为 'cookies.pkl' 的文件。在这种情况下，你可以尝试以下方法来解决权限问题：

以管理员身份运行脚本：以管理员权限运行你的 Python 脚本，这样脚本将具有足够的权限来创建和写入文件。在 Windows 上，右键单击脚本文件，然后选择 "以管理员身份运行"。

更改文件保存路径：将 'cookies.pkl' 文件保存到具有写入权限的其他目录。你可以使用绝对文件路径来指定保存的位置，例如：

python
Copy code
# 在保存 Cookies 时使用绝对路径
with open('C:/path/to/your/folder/cookies.pkl', 'wb') as fw:
    # 写入 Cookies 数据
确保 'C:/path/to/your/folder/' 是你具有写入权限的文件夹路径。
