### ISSUE TITLE
给驱动everyone权限了，为什么还报错

### ISSUE THREAD

**Issue by u-raison** [MakiNaruto/Automatic_ticket_purchase#41]
chromedriver_windows目录已经是everyone可读写权限了，为什么还会报错。

`C:\Automatic_ticket_purchase>python Automatic_ticket_purchase.py
Traceback (most recent call last):
  File "C:\Python3.10.9\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Python3.10.9\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python3.10.9\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] 拒绝访问。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Automatic_ticket_purchase\Automatic_ticket_purchase.py", line 315, in <module>
    a.run()
  File "C:\Automatic_ticket_purchase\Automatic_ticket_purchase.py", line 235, in run
    self.login_cookies = tools.account_login('account', self.login_id, self.login_password)
  File "C:\Automatic_ticket_purchase\tools.py", line 100, in account_login
    driver = webdriver.Chrome(chromedriver, options=option)
  File "C:\Python3.10.9\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Python3.10.9\lib\site-packages\selenium\webdriver\common\service.py", line 86, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver_windows' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

`

**Comment by Gavin-U** [comment]
我也是这个问题，麻烦问一下怎么回事

**Comment by CWH6** [comment]
> 我也是这个问题，麻烦问一下怎么回事

解决了吗？我也是这个问题，人麻了

**Comment by jyk0201** [comment]
这边大麦bp，脚本，代码和猫眼bp可长期提供，有需要的来➕q2814249606，备注github。主打信任不扯皮
