### ISSUE TITLE
谷歌内核下载根目录还是跑不起来，求指点！！！！！！！！！！！！！！

### ISSUE THREAD

**Issue by Gavin-U** [MakiNaruto/Automatic_ticket_purchase#50]
谷歌内核下载根目录还是跑不起来，求指点！！！！！！！！！！！！！！

**Comment by Tylerzhr** [comment]
改名了吗，报错提示发出来看看

**Comment by taoziganbei** [comment]
selenium.common.exceptions.WebDriverException: Message: 'chromedriver_windows' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by taoziganbei** [comment]
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "D:\Anaconda3\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "D:\Anaconda3\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
PermissionError: [WinError 5] 拒绝访问。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/Automatic_ticket_purchase/Automatic_ticket_purchase.py", line 315, in <module>
    a.run()
  File "E:/Automatic_ticket_purchase/Automatic_ticket_purchase.py", line 235, in run
    self.login_cookies = tools.account_login('account', self.login_id, self.login_password)
  File "E:\Automatic_ticket_purchase\tools.py", line 100, in account_login
    driver = webdriver.Chrome(chromedriver, options=option)
  File "D:\Anaconda3\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "D:\Anaconda3\lib\site-packages\selenium\webdriver\common\service.py", line 88, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver_windows' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by bomei** [comment]
看着像是exe文件的权限没给够，在windows下不应该啊

**Comment by xiaoyao123456789** [comment]
直接下载Edge了，改下那块代码别用谷歌，给绝对路径就好了

**Comment by taoziganbei** [comment]
> 看着像是exe文件的权限没给够，在windows下不应该啊

弄好了，在调用程序那里直接给了绝对路径，相对路径 老出问题不知道 为啥

**Comment by taoziganbei** [comment]
> 直接下载Edge了，改下那块代码别用谷歌，给绝对路径就好了

对的，直接给绝对路径，相对路径老出错

**Comment by xiaoyao123456789** [comment]
> > 直接下载Edge了，改下那块代码别用谷歌，给绝对路径就好了
> 
> 对的，直接给绝对路径，相对路径老出错

不过 是不是跑起来 也没用 所有的都不支持该渠道抢票。

**Comment by wwlwwl2000** [comment]
这边大麦脚本可长期提供，有需要的来➕q2091248098，标明github

**Comment by jyk0201** [comment]
这边大麦bp可长期提供，有需要的来➕q2814249606，标明github

**Comment by jyk0201** [comment]
这边大麦bp可长期提供，有需要的来➕q2814249606，标明github
