### ISSUE TITLE
打开chrome的页面了但是错误

### ISSUE THREAD

**Issue by zihfvhd** [MakiNaruto/Automatic_ticket_purchase#64]
Traceback (most recent call last):
  File "D:\pythonwork\test1\Automatic_ticket_purchase-master\Automatic_ticket_purchase.py", line 316, in <module>
    a.run()
  File "D:\pythonwork\test1\Automatic_ticket_purchase-master\Automatic_ticket_purchase.py", line 236, in run
    self.login_cookies = tools.account_login('account', self.login_id, self.login_password)
  File "D:\pythonwork\test1\Automatic_ticket_purchase-master\tools.py", line 100, in account_login
    driver = webdriver.Chrome(chromedriver, options=option)
  File "D:\pythonwork\test1\venv\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "D:\pythonwork\test1\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "D:\pythonwork\test1\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\pythonwork\test1\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\pythonwork\test1\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: unable to discover open pages
  (Driver info: chromedriver=2.0,platform=Windows NT 6.2 x86_64)

进程已结束,退出代码1

**Comment by zihfvhd** [comment]
<img width="788" alt="8ee44f3afbd80d6383912b915d95ae7" src="https://github.com/MakiNaruto/Automatic_ticket_purchase/assets/129043907/b28b76da-ea71-4b06-955a-953cdf1abbe3">

**Comment by Beiyues** [comment]
没人回答，太早的东西了
