### ISSUE TITLE
运行报错 all_ticket_sku = ticket_info['perform']['skuList']

### ISSUE THREAD

**Issue by yokosogithub** [MakiNaruto/Automatic_ticket_purchase#88]
python3 Automatic_ticket_purchase.py

Traceback (most recent call last):
  File "Automatic_ticket_purchase.py", line 315, in <module>
    a.run()
  File "Automatic_ticket_purchase.py", line 253, in run
    ticket_info, sku_id_sequence, sku_id = self.step1_get_order_info(self.item_id, commodity_param,
  File "Automatic_ticket_purchase.py", line 60, in step1_get_order_info
    all_ticket_sku = ticket_info['perform']['skuList']
KeyError: 'perform'

**Comment by Wz0629** [comment]
打印下 ticket_info 估计是返回失败了
